### ISSUE TITLE
EmuNAND9-20160606-224510 on N3DSXL

### ISSUE THREAD

**Issue by iMac2go** [d0k3/EmuNAND9#17]
Hi,
im trying to hack my 3ds with this Guide : https://github.com/Plailect/Guide/wiki
Part 3 - RedNAND

but some i cant go further then step 7/10 (Complete RedNAND setup) - if im entering that option and pressing  "A" to start it, nothing happens...

anyone has an idea? 

[https://abload.de/img/imagev0odq.jpeg]
[https://abload.de/img/imagey3uee.jpeg]

**Comment by xy2i** [comment]
Read the text (the one starting from the 7th line starting from the top, in white letters on a black background, continuing up to the 10th's line on the New 3DS XL's screen), there you will find instructions how to solve this issue.

**Comment by d0k3** [comment]
You are serious, right? Do what xy2iii said and **read the text on screen**.  And next time, at least try to help yourself before posting an issue. The issues function on GitHub is for bugs and feature requests rather than handholding through the a9lh process.

If there is more to this issue than you not reading the screen, feel free to reopen.

**Comment by iMac2go** [comment]
yeah sorry.. my fault .... i just made it ... sorry sorry sorry

**Comment by d0k3** [comment]
Well, it's alright, but try to help yourself first next time ;).
