### ISSUE TITLE
Request: Make EmuNAND9 boot9strap compatible

### ISSUE THREAD

**Issue by kamenrider-darkglass** [d0k3/EmuNAND9#21]
I know that EmuNAND9 is discontinued technically, but its user friendliness in making redNANDs and Gateway-type EmuNANDs is what makes it appealing over Godmode9. Could you find it in your heart to make just one more release for boot9strap since B9S doesn't support .bin files?

You did so for hourglass9, so I thought it wouldn't be too much to ask to make the same request for EmuNAND9.

**Comment by ghost** [comment]
I'm with you. I missed EmuNAND9 after upgrading from A9LH to B9S and I wanna use it again. Tried using Firmtool to convert .bin to .firm payloads and it crashes when trying to boot...

**Comment by d0k3** [comment]
And here's to using outdated / legacy software. The EmuNAND9 codebase is completely outdated, and updating / testing it for b9s is something I won't waste time with. Take a look at the last few commits for D9WIP / HG9 for ideas on how to do it and do it yourself.

Only leaving this open cause someone may want to do a pull request.

**Comment by CaiMiao** [comment]
@d0k3 But G9 is lacking some functions, like
- convert RedNand to EmuNand GW
- clone SysNand to EmuNand
If you can add it to G9, that's great.

**Comment by Conan179** [comment]
I use emunand9 to format my sd card for emunand (o3ds and n3ds XL). D9WIP & HG9 dosnt have this option. I have found a way to load a emunand.bin over a CtrBootManager9 version and b9s.

**Comment by mariogamer2** [comment]
@CaiMiao first one: I understand that d0k3 won't add it.... useless, and also why using GW sh*t...

Second one is already implemented no?

**Comment by mariogamer2** [comment]
Yep already implemented.

**Comment by Conan179** [comment]
Then just missing:
1. Converting Rednand to Emunand (and or back)
2. SD card formatting.

**Comment by mariogamer2** [comment]
@Conan179 second one is already implemented (no emunand format)

EmuNAND is basically gw emunand? so same than what I just said...

**Comment by Conan179** [comment]
yes emunand format is the gw nand.
And where is the option for formatting? I can not find any.

**Comment by mariogamer2** [comment]
Go to: Home menu -> More... -> SD format menu -> No EmuNAND

**Comment by Conan179** [comment]
this funktion are missing in Decrypt9 and hourglass9.
I have a gateway card and have needed to format with emunand9.

**Comment by CaiMiao** [comment]
@mariogamer2  

1. Accidentally I chose RedNand to setup the emunand. Without E9, the only way to change is formatting SD card, which means you must **backup many boring things**.
2. The sys->emu nand clone only implemented in the process of formatting SD card, which means you must **backup many boring things** and clone sys->emu one-way.

I just want the world funnier, less boring.

**Comment by d0k3** [comment]
Mind if I remind you Github issues is not a forum? This issue is only kept open *in case another dev wants to fix EmuNAND9*. It is especially not open for "I didn't get myself informed and I think GM9 can't do that". Add something useful to this issue (which is almost impossible at that point), find a dev who will fix this for you, or fix it yourself.

Anyways - you know GW EmuNAND needs more room than RedNAND? It's format anew one way or another. If you ask me, get it right the first time, and if you don't, don't abuse Github issues to vent your frustration.

Also, that converter thing? It was gimicky all the way. There's not much reason to move from GW EmuNAND -> RedNAND, and the other way around does not work because of the size restriction (s.o.). Also... who in their right mind does still buy a GW card in 2017 and has to convert his RedNAND?

Cloning SysNAND to EmuNAND works the same way you do a copy of your NAND backup, *by copying `nand.bin` or `nand_minsize.bin`* to `E:/`.

**Comment by Jerry-Shaw** [comment]
Just made a quick modification for B9S, but needs to update the submodules to compile. Need test also.

**Comment by d0k3** [comment]
Alright... @Jerry-Shaw - can you update the submodules, too? It's (in git command line):
cd [submodule_dir]
git stash
git stash drop
git checkout master
git fetch
git pull

Do this for each of the 3 submodules, thern commit the change.

Also, provide a release build (make release) here, so that users can test.

**Comment by Jerry-Shaw** [comment]
OK, wait a moment.

**Comment by Jerry-Shaw** [comment]
BTW, why github doesn't support .zip compressed by 7z?
I just committed the changes but cannot upload files...

**Comment by Jerry-Shaw** [comment]
I'll try tomorrow.

**Comment by ghost** [comment]
Wouldn't it not be ideal to just, update EN9 to support .firm? for use with luma chainloader :v

**Comment by Jerry-Shaw** [comment]
Alright, the release pack for B9S goes here (Uploading always failed here)...
https://github.com/Jerry-Shaw/EmuNAND9/releases/tag/20170911

People who need it, make tests please. And thanks @d0k3 .

I personally tests the NAND backup to file functions, both EmuNAND and SysNAND worked.
Don't try to restore the SysNAND if you don't have A9 or B9. I don't know if there is any bug in there.

**Comment by d0k3** [comment]
Last time I checked, EmuNAND9 didn't even have an option to restore the SysNAND ;). if you mean restoring the dumps made by EmuNAND9 in other tools, that should be fine with the safe restore option.

**Comment by Jerry-Shaw** [comment]
Ha-ha, yep, that is what exact I meant. But I remembered one thing happend long ago, cannot remember clearly. When I tried to restore an Emunand dump file created by Decrypt9 via EmuNAND9, it showed failed. But all is gone now, too many ways to do it now.

**Comment by d0k3** [comment]
Solved by @Jerry-Shaw's pull request.
